### ISSUE TITLE
Can I embed this C library to perform USB communication with ARM M7?

### ISSUE THREAD

**Issue by raggot** [ingeniamc/ingenialink#11]
Hi,

Is it possible to use this C library in an embedded environment? More specifically, I'd like to use it with an ATMEL SAM E70 (ARM M7 family) microcontroller.

Moreover, I'm not 100% sure this implies microUSB communication from 1 master to 1 slave only, or if it's possible to use a bus protocol with it (for example, CAN). I need to steer 4 motors (4 drives) with my microcontroller.

Thanks in advance.

**Comment by rjuanpere** [comment]
Hi @raggot,

In your case I believe that make sense to use our CORE products with SPI interface an communicate using MCB protocol.
Take a look at 
https://doc.ingeniamc.com/display/EVECORE/Product+Description

We provide also an MCB library to simplify the integration
https://github.com/ingeniamc/mcblib

Regards,
Roger

**Comment by rjuanpere** [comment]
Not an issue
