### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by jmorrison74** [ingeniamc/ingenialink#6]
Hi,

I need to start a project with one of your servo drives that uses an embedded Linux board as a master, but I see that your libraries are somewhat abandoned. While there seems to be activity on some branches, I am worried that some of these changes get into master because of their poor quality.

So my questions are:

- Are you going to produce regular releases for the next 2-3 years?
- Are you going to keep the API consistent?
- Are you going to continue support for Linux?

Thanks in advance.

**Comment by oriolbv** [comment]
No, it's not abandoned.
We are gonna produce regular releases during the next years and branches will not be merged until they are not totally verified. 
Don't worry about changes in the API, it'll not change for EUSB protocol.
Also, we'll continue supporting Linux in the master branch.

Best regards

**Comment by jmorrison74** [comment]
Thank you for your answers. However we have finally decided to use another servo drive brand with better SDK support.
